package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.database.DatabaseUtils;
import ru.itmo.wp.model.domain.Article;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.ArticleRepository;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ArticleRepositoryImpl implements ArticleRepository {

    private final DataSource DATA_SOURCE = DatabaseUtils.getDataSource();
    @Override
    public Article find(long id) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM Article WHERE id=?")) {
                statement.setLong(1, id);
                try (ResultSet resultSet = statement.executeQuery()) {
                    return toArticle(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find Article.", e);
        }
    }

    @Override
    public void save(Article article) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("INSERT INTO `Article` (`userId`, `title`, `text`, `creationTime`) VALUES (?, ?, ?, NOW())", Statement.RETURN_GENERATED_KEYS)) {
                statement.setString(1, Long.toString(article.getUserId()));
                statement.setString(2, article.getTitle());
                statement.setString(3, article.getText());

                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save Article.");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        article.setId(generatedKeys.getLong(1));
                        article.setCreationTime(find(article.getId()).getCreationTime());
                    } else {
                        throw new RepositoryException("Can't save Article [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save Article.", e);
        }
    }

    public List<Article> getAllArticles() {
        List<Article> items = new ArrayList<>();
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM `Article` ORDER BY creationTime DESC")) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    Article item;
                    while ((item = toArticle(resultSet.getMetaData(), resultSet)) != null) {
                        items.add(item);
                    }
                }
            } catch (SQLException e) {
                throw new RepositoryException("Can't get all articles from DB", e);
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't get all articles from DB", e);
        }
        return items;
    }

    public List<Article> getAllNotHidden() {
        List<Article> items = new ArrayList<>();
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM `Article` WHERE `hidden`=false ORDER BY `creationTime` DESC")) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    Article item;
                    while ((item = toArticle(resultSet.getMetaData(), resultSet)) != null) {
                        items.add(item);
                    }
                }
            } catch (SQLException e) {
                throw new RepositoryException("Can't get all articles from DB", e);
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't get all articles from DB", e);
        }
        return items;
    }

    private Article toArticle(ResultSetMetaData metaData, ResultSet resultSet) throws SQLException {
        if (!resultSet.next()) {
            return null;
        }

        Article article = new Article();
        for (int i = 1; i <= metaData.getColumnCount(); i++) {
            switch (metaData.getColumnName(i)) {
                case "id":
                    article.setId(resultSet.getLong(i));
                    break;
                case "title":
                    article.setTitle(resultSet.getString(i));
                    break;
                case "text":
                    article.setText(resultSet.getString(i));
                    break;
                case "creationTime":
                    article.setCreationTime(resultSet.getTimestamp(i));
                    break;
                case "userId":
                    article.setUserId(resultSet.getLong(i));
                    break;
                case "hidden":
                    article.setHidden(resultSet.getBoolean(i));
                    break;
                default:
                    // No operations.
            }
        }

        return article;
    }

    public void setHidden(long id) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("UPDATE `Article` SET `hidden`=? WHERE `id`=?")) {
                statement.setBoolean(1, true);
                statement.setLong(2, id);

                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save Article.");
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save Article.", e);
        }
    }

    public void setShow(long id) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("UPDATE `Article` SET `hidden`=? WHERE `id`=?")) {
                statement.setBoolean(1, false);
                statement.setLong(2, id);

                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save Article.");
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save Article.", e);
        }
    }

    public List<Article> getByUserId(long userId) {
        List<Article> items = new ArrayList<>();
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM `Article` WHERE `userId`=?")) {
                statement.setString(1, Long.toString(userId));
                try (ResultSet resultSet = statement.executeQuery()) {
                    Article item;
                    while ((item = toArticle(resultSet.getMetaData(), resultSet)) != null) {
                        items.add(item);
                    }
                }
            } catch (SQLException e) {
                throw new RepositoryException("Can't get all articles from DB", e);
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't get all articles from DB", e);
        }
        return items;
    }
}
